// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVkFb_gs3MBTkTGBvKsbRS6xQWwv81KYA',
    appId: '1:861948042895:web:cda0f78064b8ce6b999afa',
    messagingSenderId: '861948042895',
    projectId: 'pawrfecto-3c8ce',
    authDomain: 'pawrfecto-3c8ce.firebaseapp.com',
    storageBucket: 'pawrfecto-3c8ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsGoWMcvqE6ZqpRLtP7GrBvBIn0FYUrJk',
    appId: '1:861948042895:android:5333551318e019d2999afa',
    messagingSenderId: '861948042895',
    projectId: 'pawrfecto-3c8ce',
    storageBucket: 'pawrfecto-3c8ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_vN0_Yis3xFq3TduXGvc75YdOd5aC4DY',
    appId: '1:861948042895:ios:cfe1d2be1903c6d6999afa',
    messagingSenderId: '861948042895',
    projectId: 'pawrfecto-3c8ce',
    storageBucket: 'pawrfecto-3c8ce.appspot.com',
    androidClientId: '861948042895-bdpaklmjhmkvd0pk1aue0du82m6j5h48.apps.googleusercontent.com',
    iosClientId: '861948042895-6httfgt1h4kp5h96q24ok2d4bh8f7ddt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawrfecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_vN0_Yis3xFq3TduXGvc75YdOd5aC4DY',
    appId: '1:861948042895:ios:cfe1d2be1903c6d6999afa',
    messagingSenderId: '861948042895',
    projectId: 'pawrfecto-3c8ce',
    storageBucket: 'pawrfecto-3c8ce.appspot.com',
    androidClientId: '861948042895-bdpaklmjhmkvd0pk1aue0du82m6j5h48.apps.googleusercontent.com',
    iosClientId: '861948042895-6httfgt1h4kp5h96q24ok2d4bh8f7ddt.apps.googleusercontent.com',
    iosBundleId: 'com.example.pawrfecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVkFb_gs3MBTkTGBvKsbRS6xQWwv81KYA',
    appId: '1:861948042895:web:f9fef5739d54e1d1999afa',
    messagingSenderId: '861948042895',
    projectId: 'pawrfecto-3c8ce',
    authDomain: 'pawrfecto-3c8ce.firebaseapp.com',
    storageBucket: 'pawrfecto-3c8ce.appspot.com',
  );

}